---
- name: Install and Configure Fail2Ban
  hosts: all
  become: yes

  tasks:
    - name: Install Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Create Fail2Ban jail.local for SSH and NGINX
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 3

          [sshd]
          enabled = true
          port = 22
          filter = sshd
          logpath = /var/log/auth.log

          [nginx-http-auth]
          enabled = true

          [nginx-dos]
          enabled = true
        owner: root
        group: root
        mode: '0644'
      notify: Restart Fail2Ban

  handlers:
    - name: Restart Fail2Ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted
