---
- name: Prepare Host for NGINX Container and SSL
  hosts: swarm_managers
  become: yes
  
  vars:
    nginx_user: www-data
    domain_name: {{ domain_name }} 
    admin_email: {{ admin_email }} 
  
  tasks:
    - name: Install NGINX and Certbot
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is started for certificate validation
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Check if SSL certificate already exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert

    - name: Obtain SSL certificate if it doesn't exist
      command: |
        certbot --nginx -d {{ domain_name }} -d www.{{ domain_name }} --non-interactive --agree-tos --email {{ admin_email }}
      when: not ssl_cert.stat.exists

    - name: Stop and disable the host NGINX service
      systemd:
        name: nginx
        state: stopped
        enabled: no
      # This is critical to prevent port conflicts with the NGINX container

    - name: Create NGINX directory for container config
      file:
        path: /etc/nginx/sites-available
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy final NGINX configuration for the container to use
      template:
        src: nginx.conf.j2 
        dest: /etc/nginx/sites-available/turbogate
        owner: root
        group: root
        mode: '0644'