version: '3.8'

services:
  turbogate:
    image: fwande/turbogate:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - FLASK_ENV=prod
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - source: turbogate_secret_key
        target: SECRET_KEY
        mode: 0400
    networks:
      - turbogate_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/gateway/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    command: redis-server --requirepass-file /run/secrets/redis_password
    secrets:
      - source: redis_password
        target: redis_password
        mode: 0400
    networks:
      - turbogate_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx_logs:/var/log/nginx
    networks:
      - turbogate_network
    depends_on:
      - turbogate
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/turbogate/redis
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/turbogate/nginx

networks:
  turbogate_network:
    driver: overlay
    attachable: true
    driver_options:
      encrypted: "true"

secrets:
  turbogate_secret_key:
    external: true
  redis_password:
    external: true